language: python

stages:
- test
- name: deploy
  if: repo = ESSS/oop-ext AND tag IS present

install:
- pip install -U pip
- pip install -U tox

script:
- tox

jobs:
  include:
  - python: '3.6'
    env: TOXENV=linting
  - python: '3.6'
    env: TOXENV=docs
  - python: '3.6'
    env: TOXENV=py36
  - python: '3.7'
    env: TOXENV=py37
    sudo: required
    dist: xenial
  - stage: deploy
    python: '3.6'
    env:
    install: pip install -U setuptools setuptools_scm
    script: skip
    deploy:
      provider: pypi
      distributions: sdist bdist_wheel
      user: lincrosenbach
      password:
        secure: j5/b7JtmPg4xCHShWKgNLDbXTqHI2aRzrGA/ItJmR+k6GQkeiIZy12N72F6vbx/b3HSJi9vfElVM9zzWQFAfxAk86FFpzDQ1K7kFv9haLDYG/z76j6x1Kq4QD1VYHiqY9G1XRBvTEUrwBROa76/vxC5vX0Mg8cqXpj4TLRD/qw6jCzUwmSY6garFRciAaa5ppyLdxgTSQEYZN04nT0YnxvIeNaXhQSWGI44HFAJTlxk9VRmbb5BGRP/bX2UIt//pdLsYfFMNIvR0qymQBeeFOf5H8yB4uGpKKmco1Qv415Pe7vvuZgeiL8ou1R2ZkmkdGu8taZzK8WPkzZ2Fe+KWl4joqgrU/jsYuNnwK0v7PHUGZEW7zj5lZcm1+68hjY90XsItrJy/RT6xquBZvfyOZeiOkKFtB5K8VgmnxnG0V5t9eflv0Kk3lwydFV+8fGKJA7CxMT0Qo+DMabbYlRSg6xy+AfiLEzE1hj5azs9ox2JYyoPSIcquHjxh8u5D3kmqh0E7R6KWtOIHSghHJ7MY3VbPb/QgnyvHVTOI+NvMP9uXVXAke0j1bZAscKZFsYdXnG58wqjKSmA0cXEgDyFUw8pPj46EC5ecbqZTGkRlY0C7tPXCaZx0eK79byS8tZL4D/55ffYbbVD70t8Glr0k11yOdSqK2WlXI/UXUQGCGaA=
      on:
        tags: true
        repo: ESSS/oop-ext
        python: 3.6
branches:
  only:
  - master
  - "/v(\\d+\\.)*\\d/"
