name: test

on:
  push:
    branches:
      - master

  pull_request:


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  package:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      attestations: write
    steps:
      - uses: actions/checkout@v4
      - name: Build and Check Package
        uses: hynek/build-and-inspect-python-package@v2.13.0
        with:
          # Disabling because this is failing currently, see #466.
          attest-build-provenance-github: 'false'

  test:

    needs: [package]

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        python: ["3.10", "3.11", "3.12", "3.13"]
        os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v4

    - name: Download Package
      uses: actions/download-artifact@v4
      with:
        name: Packages
        path: dist

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python }}

    - name: Install tox
      run: |
        python -m pip install --upgrade pip
        pip install tox

    - name: Test
      shell: bash
      run: |
        tox run -e py --installpkg `find dist/*.tar.gz`

  sonarcloud:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.2.2
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
